import { safeReply, safeDefer } from '../utils/responses.js';
import { SlashCommandBuilder, EmbedBuilder, Attachment, AttachmentBuilder, MessageFlags } from 'discord.js';
import { solveDoubt } from '../../lib/gemini.js';

export default {
  data: new SlashCommandBuilder()
    .setName('doubt_solver')
    .setDescription('❓ Solve any Class 10 doubt instantly with ScholarAI (Supports image attachments)')
    .addStringOption(option =>
      option.setName('query')
        .setDescription('Type your question or academic doubt')
        .setRequired(false)
    )
    .addAttachmentOption(option =>
      option.setName('image')
        .setDescription('Upload a photo or screenshot of the question')
        .setRequired(false)
    ),

  async execute(interaction: any) {
    const query = interaction.options.getString('query') || '';
    const attachment = interaction.options.getAttachment('image') as Attachment;

    if (!query && !attachment) {
      return await safeReply(interaction, {
        content: '❌ **Please provide either a written question/query or upload an image attachment of your doubt.**'
      });
    }

    // Immediately defer the reply to prevent Discord interaction timing out (3 second gateway limit)
    await safeDefer(interaction, false);

    try {
      // 1. Download and convert attachment if present
      let imageBase64: string | null = null;
      if (attachment) {
        if (!attachment.contentType?.startsWith('image/')) {
          return await safeReply(interaction, {
            content: '❌ **Invalid attachment format.** Please upload a valid image file (PNG, JPEG, WEBP).'
          });
        }
        
        try {
          const res = await fetch(attachment.url);
          if (!res.ok) throw new Error(`HTTP status ${res.status}`);
          const buffer = Buffer.from(await res.arrayBuffer());
          imageBase64 = `data:${attachment.contentType};base64,${buffer.toString('base64')}`;
        } catch (downloadErr: any) {
          console.error('[Doubt Solver] Failed to download image attachment:', downloadErr);
          return await safeReply(interaction, {
            content: `❌ **Failed to download the image file.** Please try re-uploading or typing details.`
          });
        }
      }

      // 2. Query Gemini API doubt solver
      console.log(`[Doubt Solver] Processing user query for ${interaction.user.username}`);
      const solution = await solveDoubt(query, imageBase64);

      if (!solution) {
        throw new Error('Emply response received from AI model.');
      }

      // Discord Embed Description limit is 4096. Let's safety chunk if response is too long.
      const embeds: EmbedBuilder[] = [];
      const cleanSolution = solution.replace(/\\\[|\\\]|\\\(|\\\)/g, '$'); // optimize LaTeX for Discord formatting
      
      const paragraphs = cleanSolution.split('\n');
      let currentDesc = '';

      for (let i = 0; i < paragraphs.length; i++) {
        const p = paragraphs[i];
        if ((currentDesc.length + p.length + 2) < 3800) {
          currentDesc += p + '\n';
        } else {
          embeds.push(
            new EmbedBuilder()
              .setTitle(embeds.length === 0 ? '🧠 SCHOLAR-AI STEP-BY-STEP RESOLUTION' : '📖 SOLUTION CONTINUED')
              .setColor(0x5865F2)
              .setDescription(currentDesc || 'No content.')
          );
          currentDesc = p + '\n';
        }
      }

      if (currentDesc) {
        embeds.push(
          new EmbedBuilder()
            .setTitle(embeds.length === 0 ? '🧠 SCHOLAR-AI STEP-BY-STEP RESOLUTION' : '📖 SOLUTION CONTINUED')
            .setColor(0x5865F2)
            .setDescription(currentDesc)
            .setFooter({ text: 'Answer generated by ScholarAI Scholar Assistant' })
        );
      }

      // Let's send results
      await safeReply(interaction, {
        embeds: embeds.slice(0, 5), // Keep max 5 embeds to avoid payload issues
      });

    } catch (err: any) {
      console.error('[Doubt Solver Error]', err);
      await safeReply(interaction, {
        content: `❌ **AI Processing Exception:** Raised unexpected error while analyzing your doubt. \n*Diagnostics: ${err.message}*`
      });
    }
  },
};
